# Cargo.toml
[package]
name = "markdown-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.14.0"
markdown = "1.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
